language: python
python:
  - "2.7"
before_install:
  - bash validator_setup.sh
install: "pip install pytz==2014.4"
script: python googletransitdatafeed/python/feedvalidator.py --output=CONSOLE --error_types_ignore_list="InvalidValue,ExpirationDate,OtherProblem,UnusedStop" gtfs.zip
